version: "3.9"

networks:
  my-custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  yolo:
    image: junwoogyun/flask-opencv-app:latest # Docker Hub 이미지
    container_name: flask-opencv-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.100
    ports:
      - "5000:5000" # YOLO Flask 포트 매핑

  predict:
    image: junwoogyun/flask-opencv-app2:latest # Docker Hub 이미지
    container_name: flask-opencv-container2
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.200
    ports:
      - "5002:5002"
      - "5003:5003"
      - "5004:5004" # Predict Flask 포트 매핑

  db:
    image: junwoogyun/mysql-custom:1.0 
    container_name: mysql8-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.30
    ports:
      - "3330:3306" 

  redis:
    image: junwoogyun/bn_redis:latest
    container_name: bn_redis-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.50
    ports:
      - "6376:6376"

  auth:
    image: junwoogyun/bn_auth:latest
    container_name: bn_auth-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.40
    ports:
      - "8095:8095" 
  fn:
    image: junwoogyun/react-docker-app:latest # Docker Hub 이미지
    container_name: react-container
    networks:
      my-custom-network:
        ipv4_address: 192.168.1.10
    ports:
      - "3000:80" # React Nginx 포트 매핑